import logging
from dataclasses import dataclass, field
from typing import Any
from uuid import UUID
import math

import numpy as np
from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.db import Assignment, Experiment, ExperimentStatus, Metric, MetricType, Variant
from app.services.stats.corrections import benjamini_hochberg
from app.services.stats.hypothesis_tests import (
    TestResult,
    check_normality,
    delta_method_test,
    mann_whitney_test,
    welch_t_test,
    z_test_proportions,
)
from app.services.stats.sample_size import (
    calculate_achieved_mde_conversion,
    calculate_achieved_mde_revenue,
)
from app.services.stats.sequential import always_valid_pvalue
from app.services.stats.srm import SRMResult, check_srm

logger = logging.getLogger(__name__)


# Data structures 

@dataclass
class VariantAnalysis:
    variant_id: UUID
    variant_name: str
    sample_size: int
    mean: float
    std_dev: float | None = None
    p_value: float | None = None
    ci_low: float | None = None
    ci_high: float | None = None
    effect_size: float | None = None
    relative_lift: float | None = None
    is_significant: bool | None = None
    is_winner: bool = False
    ai_interpretation: str | None = None
    is_normal: bool | None = None
    normality_p_value: float | None = None
    test_used: str | None = None
    achieved_mde: float | None = None
    numerator_mean: float | None = None           # среднее числителя на юзера
    denominator_mean: float | None = None         # среднее знаменателя на юзера
    numerator_relative_lift: float | None = None  # относительный lift числителя %
    denominator_relative_lift: float | None = None # относительный lift знаменателя %
    sequential_fpr: float | None = None            # mSPRT always-valid p-value
    sequential_boundary_crossed: bool | None = None  # True iff sequential_fpr < alpha


@dataclass
class MetricAnalysis:
    metric_id: UUID
    metric_name: str
    metric_type: str
    is_primary: bool
    is_guardrail: bool
    srm: SRMResult
    variants: list[VariantAnalysis] = field(default_factory=list)
    guardrail_violated: bool = False
    # M-011: count of warning-severity guardrail firings (informational,
    # does not block winners). Filled by guardrail_service evaluation.
    guardrail_warning_count: int = 0


@dataclass
class ExperimentAnalysis:
    """Top-level analysis result — metrics + rule-based insights."""
    metrics: list[MetricAnalysis]
    insights: list = field(default_factory=list)  # list[Insight] (filled by interpreter)


# DB queries 

async def _get_variant_counts(
    db: AsyncSession, experiment_id: UUID
) -> dict[str, dict]:
    result = await db.execute(
        select(
            Variant.id,
            Variant.name,
            Variant.traffic_split,
            func.count(Assignment.id).label("count"),
        )
        .outerjoin(Assignment, Assignment.variant_id == Variant.id)
        .where(Variant.experiment_id == experiment_id)
        .group_by(Variant.id, Variant.name, Variant.traffic_split)
    )
    return {
        row.name: {
            "id": row.id,
            "count": row.count or 0,
            "traffic_split": row.traffic_split,
        }
        for row in result
    }


async def _get_conversion_data(
    db: AsyncSession,
    experiment_id: UUID,
    event_name: str,
    *,
    filters: list | None = None,
) -> dict[str, tuple[int, int]]:
    """
    Return {variant_name: (total_users, converted_users)}.

    M-011: `filters` is an AND-combined list of {field, operator, value}
    matchers applied to `events.properties` JSONB. Generated by
    `custom_metric_service.build_filter_clause`.
    """
    params: dict[str, Any] = {
        "experiment_id": str(experiment_id),
        "event_name":    event_name,
    }
    filter_clause, _ = _build_metric_filter_clause(
        filters, alias="e", params=params, prefix="cnv",
    )
    sql = f"""
        SELECT
            a.variant_name,
            COUNT(DISTINCT a.user_id)                                      AS total_users,
            COUNT(DISTINCT CASE WHEN e.user_id IS NOT NULL
                                THEN a.user_id END)                        AS converted_users
        FROM assignments a
        LEFT JOIN events e
               ON e.user_id     = a.user_id
              AND e.event_name  = :event_name
              AND e.occurred_at >= a.assigned_at{filter_clause}
        WHERE a.experiment_id = :experiment_id
        GROUP BY a.variant_name
    """
    rows = await db.execute(text(sql), params)
    return {r.variant_name: (r.total_users, r.converted_users) for r in rows}


async def _get_revenue_data(
    db: AsyncSession,
    experiment_id: UUID,
    event_name: str,
    *,
    filters: list | None = None,
) -> dict[str, list[float]]:
    """Return {variant_name: [value_per_user, ...]}.

    M-011: optional `filters` applied to `events.properties` (same shape
    as `_get_conversion_data`).
    """
    params: dict[str, Any] = {
        "experiment_id": str(experiment_id),
        "event_name":    event_name,
    }
    filter_clause, _ = _build_metric_filter_clause(
        filters, alias="e", params=params, prefix="rev",
    )
    sql = f"""
        SELECT
            a.variant_name,
            a.user_id,
            COALESCE(SUM(e.value), 0) AS total_value
        FROM assignments a
        LEFT JOIN events e
               ON e.user_id     = a.user_id
              AND e.event_name  = :event_name
              AND e.occurred_at >= a.assigned_at
              AND e.value IS NOT NULL{filter_clause}
        WHERE a.experiment_id = :experiment_id
        GROUP BY a.variant_name, a.user_id
    """
    rows = await db.execute(text(sql), params)
    data: dict[str, list[float]] = {}
    for row in rows:
        data.setdefault(row.variant_name, []).append(float(row.total_value))
    return data


async def _get_ratio_data(
    db: AsyncSession,
    experiment_id: UUID,
    numerator_event: str,
    denominator_event: str,
    *,
    numerator_filters: list | None = None,
    denominator_filters: list | None = None,
) -> dict[str, tuple[list[float], list[float]]]:
    """
    Return {variant_name: (numerator_per_user[], denominator_per_user[])}.

    numerator_event:   event_name числителя (например "purchase", value = сумма покупки)
    denominator_event: event_name знаменателя (например "session_start"):
        - value != NULL → используем value
        - value == NULL → считаем каждое событие как 1 (count semantics)

    M-011: `numerator_filters`/`denominator_filters` apply independently
    to the two events so e.g. "purchases in EU / sessions in EU" works.

    Каждый assigned пользователь присутствует в результате (LEFT JOIN).
    Пользователи без событий получают (0, 0).
    """
    from app.services.custom_metric_service import build_filter_clause

    # All three builders share `params` so the bind names registered
    # below match the placeholders in the final SQL.
    params: dict[str, Any] = {
        "experiment_id": str(experiment_id),
        "num_event":     numerator_event,
        "den_event":     denominator_event,
    }
    num_event_case = _ratio_event_predicate(
        "e.event_name = :num_event", numerator_filters, "num", params,
    )
    den_event_case = _ratio_event_predicate(
        "e.event_name = :den_event", denominator_filters, "den", params,
    )
    sql = f"""
        SELECT
            a.variant_name,
            a.user_id,
            COALESCE(SUM(
                CASE WHEN {num_event_case}
                     THEN COALESCE(e.value, 0) ELSE 0 END
            ), 0) AS numerator,
            COALESCE(SUM(
                CASE WHEN {den_event_case}
                     THEN COALESCE(e.value, 1) ELSE 0 END
            ), 0) AS denominator
        FROM assignments a
        LEFT JOIN events e
               ON e.user_id     = a.user_id
              AND (e.event_name = :num_event OR e.event_name = :den_event)
              AND e.occurred_at >= a.assigned_at
        WHERE a.experiment_id = :experiment_id
        GROUP BY a.variant_name, a.user_id
    """
    rows = await db.execute(text(sql), params)
    data: dict[str, tuple[list[float], list[float]]] = {}
    for row in rows:
        vn = row.variant_name
        if vn not in data:
            data[vn] = ([], [])
        data[vn][0].append(float(row.numerator))
        data[vn][1].append(float(row.denominator))
    return data


# M-011 helpers (filter clause builders reused by the three loaders above)
# ─────────────────────────────────────────────────────────────────────────

def _build_metric_filter_clause(
    filters: list | None,
    *,
    alias: str,
    params: dict[str, Any],
    prefix: str,
) -> tuple[str, int]:
    """
    Thin wrapper around `custom_metric_service.build_filter_clause` so
    this module doesn't have to import the service (and the implicit
    dependency) at module load. The service does the heavy lifting.
    """
    from app.services.custom_metric_service import build_filter_clause
    return build_filter_clause(filters, alias=alias, params=params, prefix=prefix)


def _ratio_event_predicate(
    event_predicate: str,
    filters: list | None,
    prefix: str,
    params: dict[str, Any],
) -> str:
    """
    Build the boolean expression used inside the ratio SQL's CASE WHEN.

    The CASE is True only when the event matches AND every filter
    clause matches. The shared `params` dict is mutated in place so the
    outer `db.execute(text(sql), params)` binds every placeholder.

    Returns just the predicate (e.g. "e.event_name = :num_event AND
    (e.properties->>'country' = :num_0)").
    """
    from app.services.custom_metric_service import build_filter_clause
    clause, _ = build_filter_clause(
        filters, alias="e", params=params, prefix=prefix,
    )
    if not clause:
        return event_predicate
    # `clause` starts with " AND " — strip it and wrap in parens so it
    # composes cleanly with the event predicate.
    inner = clause.strip().lstrip("AND").strip()
    return f"{event_predicate} AND ({inner})"


# Core analysis helpers 

def _find_control(variant_counts: dict[str, dict]) -> str:
    if "control" in variant_counts:
        return "control"
    return sorted(variant_counts.keys())[0]


def _apply_test_result(analysis: VariantAnalysis, test: TestResult) -> None:
    analysis.p_value = test.p_value
    analysis.ci_low = test.ci_low
    analysis.ci_high = test.ci_high
    analysis.effect_size = test.effect_size
    analysis.relative_lift = test.relative_lift
    analysis.is_significant = test.is_significant
    analysis.test_used = test.test_used


def _compute_achieved_mde(
    metric_type: MetricType,
    variant_analysis: VariantAnalysis,
    control_analysis: VariantAnalysis,
) -> float | None:
    """
    MDE при текущей выборке (post-experiment).

    Для ratio метрик: control_analysis.std_dev содержит std линеаризованных
    значений Z (установлено в run_analysis после delta_method_test).
    Это корректно — дисперсия ratio estimator отражена в std(Z).
    """
    n = min(variant_analysis.sample_size, control_analysis.sample_size)
    try:
        if metric_type == MetricType.CONVERSION:
            if 0.0 < control_analysis.mean < 1.0:
                mde = calculate_achieved_mde_conversion(n, control_analysis.mean)
                return None if math.isinf(mde) else mde

        elif metric_type in (MetricType.REVENUE, MetricType.DURATION):
            std = control_analysis.std_dev or variant_analysis.std_dev
            if std and std > 0:
                mde = calculate_achieved_mde_revenue(n, std)
                return None if math.isinf(mde) else mde

    except Exception as e:
        logger.warning(f"MDE расчёт не удался: {e}")

    return None


def _maybe_sequential(
    is_sequential: bool,
    alpha: float,
    control_values: list[float] | None,
    treatment_values: list[float] | None,
) -> tuple[float | None, bool | None]:
    """
    Compute mSPRT always-valid p-value when the experiment is sequential.

    Returns (None, None) for non-sequential experiments, insufficient samples,
    or any internal failure — sequential is opt-in, never blocks analysis.
    """
    if not is_sequential:
        return None, None
    if control_values is None or treatment_values is None:
        return None, None
    try:
        result = always_valid_pvalue(
            control_values, treatment_values, alpha=alpha,
        )
    except Exception as e:
        logger.warning(f"mSPRT расчёт не удался: {e}")
        return None, None
    if result is None:
        return None, None
    return result.always_valid_pvalue, result.boundary_crossed


# Main analysis 

async def run_analysis(
    db: AsyncSession,
    experiment_id: UUID,
) -> list[MetricAnalysis]:
    """
    Полный анализ эксперимента.

    Для каждой метрики:
    - Conversion:        Z-тест для пропорций
    - Revenue/Duration:  Shapiro-Wilk → Welch t-test (нормальное) или
                         Mann-Whitney (ненормальное, n < 5000)
    - Ratio (с denominator_event_name):
                         Delta method (линеаризация Тейлора) +
                         декомпозиция числитель/знаменатель
    - Все treatment:     MDE post-experiment
    - Primary метрики:   BH коррекция на множественные сравнения
    """
    exp_result = await db.execute(
        select(Experiment)
        .options(selectinload(Experiment.variants), selectinload(Experiment.metrics))
        .where(Experiment.id == experiment_id)
    )
    experiment = exp_result.scalar_one_or_none()
    if not experiment:
        raise ValueError(f"Эксперимент {experiment_id} не найден")

    variant_counts = await _get_variant_counts(db, experiment_id)
    if not variant_counts:
        raise ValueError("Нет назначений — анализ невозможен")

    control_name = _find_control(variant_counts)

    srm = check_srm(
        observed_counts={name: data["count"] for name, data in variant_counts.items()},
        expected_splits={name: data["traffic_split"] for name, data in variant_counts.items()},
    )
    if srm.srm_detected:
        logger.warning(f"SRM обнаружен в эксперименте {experiment_id}: p={srm.p_value:.4f}")

    metric_results: list[MetricAnalysis] = []
    all_primary_p_values: list[float] = []
    primary_analyses: list[tuple[MetricAnalysis, VariantAnalysis]] = []

    for metric in experiment.metrics:
        metric_analysis = MetricAnalysis(
            metric_id=metric.id,
            metric_name=metric.name,
            metric_type=metric.metric_type.value,
            is_primary=metric.is_primary,
            is_guardrail=metric.is_guardrail,
            srm=srm,
        )

        #  Conversion
        if metric.metric_type == MetricType.CONVERSION:
            conv_data = await _get_conversion_data(
                db, experiment_id, metric.event_name,
                filters=metric.filters,
            )

            for variant_name, v_data in variant_counts.items():
                total, converted = conv_data.get(variant_name, (0, 0))
                va = VariantAnalysis(
                    variant_id=v_data["id"],
                    variant_name=variant_name,
                    sample_size=total,
                    mean=converted / total if total > 0 else 0.0,
                    test_used="z_test" if variant_name != control_name else None,
                )

                if variant_name != control_name and variant_name in conv_data:
                    c_total, c_conv = conv_data.get(control_name, (0, 0))
                    test = z_test_proportions(c_conv, c_total, converted, total)
                    if test:
                        _apply_test_result(va, test)

                    # mSPRT (sequential) — reconstruct Bernoulli arrays.
                    # For proportion tests each assigned user is modelled as
                    # a 0/1 draw; identity is irrelevant for the statistic.
                    if experiment.is_sequential:
                        ctrl_arr = np.concatenate([
                            np.ones(c_conv, dtype=float),
                            np.zeros(max(c_total - c_conv, 0), dtype=float),
                        ]).tolist()
                        trt_arr = np.concatenate([
                            np.ones(converted, dtype=float),
                            np.zeros(max(total - converted, 0), dtype=float),
                        ]).tolist()
                        va.sequential_fpr, va.sequential_boundary_crossed = (
                            _maybe_sequential(experiment.is_sequential, 0.05,
                                              ctrl_arr, trt_arr)
                        )

                metric_analysis.variants.append(va)

        #  Revenue / Duration 
        elif metric.metric_type in (MetricType.REVENUE, MetricType.DURATION):

            #  Ratio метрика: Delta method
            if metric.denominator_event_name:
                ratio_data = await _get_ratio_data(
                    db, experiment_id,
                    metric.event_name, metric.denominator_event_name,
                    numerator_filters=metric.filters,
                    # Denominator filters live on the CustomMetric template
                    # when the metric was snapshotted; for now we mirror
                    # the numerator filters so an EU purchase-per-session
                    # metric filters both sides by EU. Refinements can be
                    # added later (denominator_filters column on Metric).
                    denominator_filters=metric.filters,
                )

                ctrl_num_list, ctrl_den_list = ratio_data.get(control_name, ([], []))
                ctrl_num = np.array(ctrl_num_list, dtype=float)
                ctrl_den = np.array(ctrl_den_list, dtype=float)

                sum_ctrl_den = float(np.sum(ctrl_den))
                theta_c = float(np.sum(ctrl_num)) / sum_ctrl_den if sum_ctrl_den > 0 else 0.0
                z_ctrl = ctrl_num - theta_c * ctrl_den
                ctrl_std_linearized = float(np.std(z_ctrl, ddof=1)) if len(z_ctrl) > 1 else None
                ctrl_num_mean = float(np.mean(ctrl_num)) if len(ctrl_num) > 0 else 0.0
                ctrl_den_mean = float(np.mean(ctrl_den)) if len(ctrl_den) > 0 else 0.0

                for variant_name, v_data in variant_counts.items():
                    trt_num_list, trt_den_list = ratio_data.get(variant_name, ([], []))
                    trt_num = np.array(trt_num_list, dtype=float)
                    trt_den = np.array(trt_den_list, dtype=float)

                    sum_trt_den = float(np.sum(trt_den))
                    theta_t = float(np.sum(trt_num)) / sum_trt_den if sum_trt_den > 0 else 0.0

                    va = VariantAnalysis(
                        variant_id=v_data["id"],
                        variant_name=variant_name,
                        sample_size=len(trt_num_list),
                        mean=theta_c if variant_name == control_name else theta_t,
                        std_dev=ctrl_std_linearized if variant_name == control_name else None,
                        numerator_mean=ctrl_num_mean if variant_name == control_name
                                       else (float(np.mean(trt_num)) if len(trt_num) > 0 else 0.0),
                        denominator_mean=ctrl_den_mean if variant_name == control_name
                                         else (float(np.mean(trt_den)) if len(trt_den) > 0 else 0.0),
                    )

                    if variant_name != control_name:
                        test = delta_method_test(
                            ctrl_num_list, ctrl_den_list,
                            trt_num_list, trt_den_list,
                        )
                        if test:
                            _apply_test_result(va, test)
                            # std линеаризованных значений для MDE
                            va.std_dev = test.std_dev_treatment

                        # Декомпозиция: относительный lift числителя и знаменателя
                        trt_num_mean = float(np.mean(trt_num)) if len(trt_num) > 0 else 0.0
                        trt_den_mean = float(np.mean(trt_den)) if len(trt_den) > 0 else 0.0
                        va.numerator_relative_lift = (
                            (trt_num_mean - ctrl_num_mean) / ctrl_num_mean * 100
                            if ctrl_num_mean != 0 else None
                        )
                        va.denominator_relative_lift = (
                            (trt_den_mean - ctrl_den_mean) / ctrl_den_mean * 100
                            if ctrl_den_mean != 0 else None
                        )
                        logger.info(
                            f"Delta method: {variant_name}/{metric.name}: "
                            f"θ_ctrl={theta_c:.4f}, θ_trt={theta_t:.4f}, "
                            f"num_lift={va.numerator_relative_lift:.1f}%, "
                            f"den_lift={va.denominator_relative_lift:.1f}%"
                            if va.numerator_relative_lift and va.denominator_relative_lift else
                            f"Delta method: {variant_name}/{metric.name}: "
                            f"θ_ctrl={theta_c:.4f}, θ_trt={theta_t:.4f}"
                        )

                    metric_analysis.variants.append(va)

            #  Обычная revenue/duration: Welch / Mann-Whitney
            else:
                rev_data = await _get_revenue_data(
                    db, experiment_id, metric.event_name,
                    filters=metric.filters,
                )
                ctrl_values = rev_data.get(control_name, [])

                for variant_name, v_data in variant_counts.items():
                    values = rev_data.get(variant_name, [])
                    va = VariantAnalysis(
                        variant_id=v_data["id"],
                        variant_name=variant_name,
                        sample_size=len(values),
                        mean=float(np.mean(values)) if values else 0.0,
                        std_dev=float(np.std(values, ddof=1)) if len(values) > 1 else None,
                    )

                    if variant_name != control_name and variant_name in rev_data:
                        is_normal_ctrl, _ = check_normality(ctrl_values)
                        is_normal_trt, norm_p_trt = check_normality(values)
                        both_normal = is_normal_ctrl and is_normal_trt

                        va.is_normal = both_normal
                        va.normality_p_value = norm_p_trt

                        if not both_normal and len(values) < 5000:
                            test = mann_whitney_test(ctrl_values, values)
                            logger.info(
                                f"Mann-Whitney выбран для {variant_name}/{metric.name}: "
                                f"is_normal_ctrl={is_normal_ctrl}, is_normal_trt={is_normal_trt}"
                            )
                        else:
                            test = welch_t_test(ctrl_values, values)

                        if test:
                            _apply_test_result(va, test)

                        # mSPRT (sequential) — per-user values feed the
                        # normal-location mixture statistic directly.
                        if experiment.is_sequential:
                            va.sequential_fpr, va.sequential_boundary_crossed = (
                                _maybe_sequential(experiment.is_sequential, 0.05,
                                                  ctrl_values, values)
                            )

                    metric_analysis.variants.append(va)

        #  MDE post-experiment 
        control_va = next(
            (va for va in metric_analysis.variants if va.variant_name == control_name),
            None,
        )
        if control_va and control_va.sample_size >= 30:
            for va in metric_analysis.variants:
                if va.variant_name == control_name:
                    continue
                va.achieved_mde = _compute_achieved_mde(metric.metric_type, va, control_va)
                if va.achieved_mde is not None:
                    logger.debug(
                        f"MDE post-exp {metric.name}/{va.variant_name}: {va.achieved_mde:.4f}"
                    )

        #  Собираем p-values для BH коррекции 
        if metric.is_primary:
            for va in metric_analysis.variants:
                if va.variant_name != control_name and va.p_value is not None:
                    all_primary_p_values.append(va.p_value)
                    primary_analyses.append((metric_analysis, va))

        metric_results.append(metric_analysis)

    #  BH коррекция по всем primary метрикам 
    if all_primary_p_values:
        corrected = benjamini_hochberg(all_primary_p_values)
        for (_, va), is_sig in zip(primary_analyses, corrected):
            va.is_significant = is_sig

    #  M-011: evaluate per-metric GuardrailConfigs against each variant.
    # When no GuardrailConfig exists for a guardrail metric, fall back to
    # the pre-M-011 behaviour (any significant negative effect = violation)
    # so experiments migrated from earlier milestones keep working.
    from app.services.guardrail_service import (
        evaluate_metric_guardrails,
        load_guardrails_grouped_by_metric,
    )

    try:
        guardrails_by_metric = await load_guardrails_grouped_by_metric(
            db, experiment_id,
        )
    except Exception as e:
        logger.warning("guardrails_load_failed", experiment_id=str(experiment_id), error=str(e))
        guardrails_by_metric = {}

    for metric_analysis in metric_results:
        if not metric_analysis.is_guardrail:
            continue
        configs = guardrails_by_metric.get(metric_analysis.metric_id, [])
        if configs:
            evaluate_metric_guardrails(metric_analysis, configs)
        else:
            # Legacy fallback: any significant negative effect = violation.
            for va in metric_analysis.variants:
                if va.variant_name == control_name:
                    continue
                if (
                    va.is_significant
                    and va.effect_size is not None
                    and va.effect_size < 0
                ):
                    metric_analysis.guardrail_violated = True
                    logger.warning(
                        f"Guardrail нарушен (legacy fallback): "
                        f"метрика={metric_analysis.metric_name}, "
                        f"вариант={va.variant_name}, effect={va.effect_size:.4f}"
                    )

    #  Победители (только если ни один guardrail не нарушен на critical)
    for metric_analysis in metric_results:
        for va in metric_analysis.variants:
            if va.variant_name == control_name:
                continue

            if metric_analysis.is_primary:
                guardrail_ok = not any(
                    m.guardrail_violated for m in metric_results if m.is_guardrail
                )
                if (
                    va.is_significant
                    and va.effect_size is not None
                    and va.effect_size > 0
                    and guardrail_ok
                ):
                    va.is_winner = True

    #  Rule-based insights (M-007) — runs once on the full metric set.
    from app.services.stats.interpreter import interpret
    insights = interpret(
        metric_results,
        alpha=0.05,
        is_sequential=experiment.is_sequential,
    )

    return ExperimentAnalysis(metrics=metric_results, insights=insights)
